// Listas expansíveis para o modo Descoberta Automática.
// Nichos priorizados para prospecção de sites/landing pages.

export const AUTO_NICHES: string[] = [
  "Clínica médica",
  "Dentista",
  "Ortodontista",
  "Psicólogo",
  "Nutricionista",
  "Fisioterapeuta",
  "Estética",
  "Salão de beleza",
  "Barbearia",
  "Veterinária",
  "Pet Shop",
  "Academia",
  "Estúdio de pilates",
  "Crossfit",
  "Restaurante",
  "Hamburgueria",
  "Pizzaria",
  "Cafeteria",
  "Confeitaria",
  "Contabilidade",
  "Escritório de advocacia",
  "Consultoria empresarial",
  "Oficina mecânica",
  "Auto Center",
  "Auto elétrica",
  "Funilaria",
  "Vidraçaria",
  "Marmoraria",
  "Marcenaria",
  "Serralheria",
  "Energia solar",
  "Climatização",
  "Ar condicionado",
  "Segurança eletrônica",
  "Dedetização",
  "Empresa de limpeza",
  "Imobiliária",
  "Construtora",
  "Arquitetura",
  "Engenharia civil",
  "Escola de idiomas",
  "Escola infantil",
  "Curso profissionalizante",
  "Fotógrafo",
  "Buffet infantil",
  "Cerimonial de casamento",
  "Transportadora",
  "Despachante",
  "Gráfica",
  "Loja de móveis planejados",
];

// Cidades brasileiras acima de ~25 mil habitantes, distribuídas por região.
// Inclui capitais, regiões metropolitanas e cidades médias.
export type CityEntry = { name: string; region: "SE" | "S" | "CO" | "NE" | "N" };

export const AUTO_CITIES: CityEntry[] = [
  // ===== SUDESTE =====
  { name: "São Paulo SP", region: "SE" },
  { name: "Guarulhos SP", region: "SE" },
  { name: "Campinas SP", region: "SE" },
  { name: "São Bernardo do Campo SP", region: "SE" },
  { name: "Santo André SP", region: "SE" },
  { name: "São José dos Campos SP", region: "SE" },
  { name: "Osasco SP", region: "SE" },
  { name: "Ribeirão Preto SP", region: "SE" },
  { name: "Sorocaba SP", region: "SE" },
  { name: "Mauá SP", region: "SE" },
  { name: "São José do Rio Preto SP", region: "SE" },
  { name: "Mogi das Cruzes SP", region: "SE" },
  { name: "Diadema SP", region: "SE" },
  { name: "Jundiaí SP", region: "SE" },
  { name: "Piracicaba SP", region: "SE" },
  { name: "Carapicuíba SP", region: "SE" },
  { name: "Bauru SP", region: "SE" },
  { name: "Itaquaquecetuba SP", region: "SE" },
  { name: "São Vicente SP", region: "SE" },
  { name: "Franca SP", region: "SE" },
  { name: "Praia Grande SP", region: "SE" },
  { name: "Guarujá SP", region: "SE" },
  { name: "Taubaté SP", region: "SE" },
  { name: "Limeira SP", region: "SE" },
  { name: "Suzano SP", region: "SE" },
  { name: "Taboão da Serra SP", region: "SE" },
  { name: "Sumaré SP", region: "SE" },
  { name: "Barueri SP", region: "SE" },
  { name: "Embu das Artes SP", region: "SE" },
  { name: "São Carlos SP", region: "SE" },
  { name: "Marília SP", region: "SE" },
  { name: "Indaiatuba SP", region: "SE" },
  { name: "Cotia SP", region: "SE" },
  { name: "Americana SP", region: "SE" },
  { name: "Araraquara SP", region: "SE" },
  { name: "Jacareí SP", region: "SE" },
  { name: "Presidente Prudente SP", region: "SE" },
  { name: "Hortolândia SP", region: "SE" },
  { name: "Santos SP", region: "SE" },
  { name: "Rio de Janeiro RJ", region: "SE" },
  { name: "São Gonçalo RJ", region: "SE" },
  { name: "Duque de Caxias RJ", region: "SE" },
  { name: "Nova Iguaçu RJ", region: "SE" },
  { name: "Niterói RJ", region: "SE" },
  { name: "Belford Roxo RJ", region: "SE" },
  { name: "Campos dos Goytacazes RJ", region: "SE" },
  { name: "São João de Meriti RJ", region: "SE" },
  { name: "Petrópolis RJ", region: "SE" },
  { name: "Volta Redonda RJ", region: "SE" },
  { name: "Magé RJ", region: "SE" },
  { name: "Macaé RJ", region: "SE" },
  { name: "Itaboraí RJ", region: "SE" },
  { name: "Cabo Frio RJ", region: "SE" },
  { name: "Nova Friburgo RJ", region: "SE" },
  { name: "Barra Mansa RJ", region: "SE" },
  { name: "Angra dos Reis RJ", region: "SE" },
  { name: "Teresópolis RJ", region: "SE" },
  { name: "Belo Horizonte MG", region: "SE" },
  { name: "Uberlândia MG", region: "SE" },
  { name: "Contagem MG", region: "SE" },
  { name: "Juiz de Fora MG", region: "SE" },
  { name: "Betim MG", region: "SE" },
  { name: "Montes Claros MG", region: "SE" },
  { name: "Ribeirão das Neves MG", region: "SE" },
  { name: "Uberaba MG", region: "SE" },
  { name: "Governador Valadares MG", region: "SE" },
  { name: "Ipatinga MG", region: "SE" },
  { name: "Sete Lagoas MG", region: "SE" },
  { name: "Divinópolis MG", region: "SE" },
  { name: "Santa Luzia MG", region: "SE" },
  { name: "Ibirité MG", region: "SE" },
  { name: "Poços de Caldas MG", region: "SE" },
  { name: "Patos de Minas MG", region: "SE" },
  { name: "Pouso Alegre MG", region: "SE" },
  { name: "Teófilo Otoni MG", region: "SE" },
  { name: "Barbacena MG", region: "SE" },
  { name: "Varginha MG", region: "SE" },
  { name: "Vitória ES", region: "SE" },
  { name: "Vila Velha ES", region: "SE" },
  { name: "Serra ES", region: "SE" },
  { name: "Cariacica ES", region: "SE" },
  { name: "Cachoeiro de Itapemirim ES", region: "SE" },
  { name: "Linhares ES", region: "SE" },
  { name: "São Mateus ES", region: "SE" },
  { name: "Colatina ES", region: "SE" },
  { name: "Guarapari ES", region: "SE" },

  // ===== SUL =====
  { name: "Curitiba PR", region: "S" },
  { name: "Londrina PR", region: "S" },
  { name: "Maringá PR", region: "S" },
  { name: "Ponta Grossa PR", region: "S" },
  { name: "Cascavel PR", region: "S" },
  { name: "São José dos Pinhais PR", region: "S" },
  { name: "Foz do Iguaçu PR", region: "S" },
  { name: "Colombo PR", region: "S" },
  { name: "Guarapuava PR", region: "S" },
  { name: "Paranaguá PR", region: "S" },
  { name: "Araucária PR", region: "S" },
  { name: "Toledo PR", region: "S" },
  { name: "Apucarana PR", region: "S" },
  { name: "Pinhais PR", region: "S" },
  { name: "Campo Largo PR", region: "S" },
  { name: "Umuarama PR", region: "S" },
  { name: "Almirante Tamandaré PR", region: "S" },
  { name: "Piraquara PR", region: "S" },
  { name: "Cambé PR", region: "S" },
  { name: "Porto Alegre RS", region: "S" },
  { name: "Caxias do Sul RS", region: "S" },
  { name: "Pelotas RS", region: "S" },
  { name: "Canoas RS", region: "S" },
  { name: "Santa Maria RS", region: "S" },
  { name: "Gravataí RS", region: "S" },
  { name: "Viamão RS", region: "S" },
  { name: "Novo Hamburgo RS", region: "S" },
  { name: "São Leopoldo RS", region: "S" },
  { name: "Rio Grande RS", region: "S" },
  { name: "Alvorada RS", region: "S" },
  { name: "Passo Fundo RS", region: "S" },
  { name: "Sapucaia do Sul RS", region: "S" },
  { name: "Uruguaiana RS", region: "S" },
  { name: "Santa Cruz do Sul RS", region: "S" },
  { name: "Cachoeirinha RS", region: "S" },
  { name: "Bagé RS", region: "S" },
  { name: "Bento Gonçalves RS", region: "S" },
  { name: "Erechim RS", region: "S" },
  { name: "Lajeado RS", region: "S" },
  { name: "Ijuí RS", region: "S" },
  { name: "Florianópolis SC", region: "S" },
  { name: "Joinville SC", region: "S" },
  { name: "Blumenau SC", region: "S" },
  { name: "São José SC", region: "S" },
  { name: "Chapecó SC", region: "S" },
  { name: "Itajaí SC", region: "S" },
  { name: "Criciúma SC", region: "S" },
  { name: "Jaraguá do Sul SC", region: "S" },
  { name: "Lages SC", region: "S" },
  { name: "Palhoça SC", region: "S" },
  { name: "Balneário Camboriú SC", region: "S" },
  { name: "Brusque SC", region: "S" },
  { name: "Tubarão SC", region: "S" },
  { name: "Camboriú SC", region: "S" },
  { name: "São Bento do Sul SC", region: "S" },
  { name: "Caçador SC", region: "S" },
  { name: "Concórdia SC", region: "S" },

  // ===== CENTRO-OESTE =====
  { name: "Brasília DF", region: "CO" },
  { name: "Taguatinga DF", region: "CO" },
  { name: "Ceilândia DF", region: "CO" },
  { name: "Goiânia GO", region: "CO" },
  { name: "Aparecida de Goiânia GO", region: "CO" },
  { name: "Anápolis GO", region: "CO" },
  { name: "Rio Verde GO", region: "CO" },
  { name: "Luziânia GO", region: "CO" },
  { name: "Águas Lindas de Goiás GO", region: "CO" },
  { name: "Valparaíso de Goiás GO", region: "CO" },
  { name: "Trindade GO", region: "CO" },
  { name: "Formosa GO", region: "CO" },
  { name: "Novo Gama GO", region: "CO" },
  { name: "Itumbiara GO", region: "CO" },
  { name: "Senador Canedo GO", region: "CO" },
  { name: "Catalão GO", region: "CO" },
  { name: "Jataí GO", region: "CO" },
  { name: "Planaltina GO", region: "CO" },
  { name: "Campo Grande MS", region: "CO" },
  { name: "Dourados MS", region: "CO" },
  { name: "Três Lagoas MS", region: "CO" },
  { name: "Corumbá MS", region: "CO" },
  { name: "Ponta Porã MS", region: "CO" },
  { name: "Naviraí MS", region: "CO" },
  { name: "Nova Andradina MS", region: "CO" },
  { name: "Cuiabá MT", region: "CO" },
  { name: "Várzea Grande MT", region: "CO" },
  { name: "Rondonópolis MT", region: "CO" },
  { name: "Sinop MT", region: "CO" },
  { name: "Tangará da Serra MT", region: "CO" },
  { name: "Cáceres MT", region: "CO" },
  { name: "Sorriso MT", region: "CO" },
  { name: "Lucas do Rio Verde MT", region: "CO" },
  { name: "Barra do Garças MT", region: "CO" },
  { name: "Primavera do Leste MT", region: "CO" },

  // ===== NORDESTE =====
  { name: "Salvador BA", region: "NE" },
  { name: "Feira de Santana BA", region: "NE" },
  { name: "Vitória da Conquista BA", region: "NE" },
  { name: "Camaçari BA", region: "NE" },
  { name: "Itabuna BA", region: "NE" },
  { name: "Juazeiro BA", region: "NE" },
  { name: "Lauro de Freitas BA", region: "NE" },
  { name: "Ilhéus BA", region: "NE" },
  { name: "Jequié BA", region: "NE" },
  { name: "Teixeira de Freitas BA", region: "NE" },
  { name: "Alagoinhas BA", region: "NE" },
  { name: "Barreiras BA", region: "NE" },
  { name: "Porto Seguro BA", region: "NE" },
  { name: "Simões Filho BA", region: "NE" },
  { name: "Paulo Afonso BA", region: "NE" },
  { name: "Eunápolis BA", region: "NE" },
  { name: "Recife PE", region: "NE" },
  { name: "Jaboatão dos Guararapes PE", region: "NE" },
  { name: "Olinda PE", region: "NE" },
  { name: "Caruaru PE", region: "NE" },
  { name: "Petrolina PE", region: "NE" },
  { name: "Paulista PE", region: "NE" },
  { name: "Cabo de Santo Agostinho PE", region: "NE" },
  { name: "Camaragibe PE", region: "NE" },
  { name: "Garanhuns PE", region: "NE" },
  { name: "Vitória de Santo Antão PE", region: "NE" },
  { name: "Igarassu PE", region: "NE" },
  { name: "Fortaleza CE", region: "NE" },
  { name: "Caucaia CE", region: "NE" },
  { name: "Juazeiro do Norte CE", region: "NE" },
  { name: "Maracanaú CE", region: "NE" },
  { name: "Sobral CE", region: "NE" },
  { name: "Crato CE", region: "NE" },
  { name: "Itapipoca CE", region: "NE" },
  { name: "Maranguape CE", region: "NE" },
  { name: "Iguatu CE", region: "NE" },
  { name: "Quixadá CE", region: "NE" },
  { name: "Pacatuba CE", region: "NE" },
  { name: "São Luís MA", region: "NE" },
  { name: "Imperatriz MA", region: "NE" },
  { name: "São José de Ribamar MA", region: "NE" },
  { name: "Timon MA", region: "NE" },
  { name: "Caxias MA", region: "NE" },
  { name: "Codó MA", region: "NE" },
  { name: "Paço do Lumiar MA", region: "NE" },
  { name: "Açailândia MA", region: "NE" },
  { name: "Bacabal MA", region: "NE" },
  { name: "Balsas MA", region: "NE" },
  { name: "Natal RN", region: "NE" },
  { name: "Mossoró RN", region: "NE" },
  { name: "Parnamirim RN", region: "NE" },
  { name: "São Gonçalo do Amarante RN", region: "NE" },
  { name: "Macaíba RN", region: "NE" },
  { name: "Ceará-Mirim RN", region: "NE" },
  { name: "Caicó RN", region: "NE" },
  { name: "Currais Novos RN", region: "NE" },
  { name: "João Pessoa PB", region: "NE" },
  { name: "Campina Grande PB", region: "NE" },
  { name: "Santa Rita PB", region: "NE" },
  { name: "Patos PB", region: "NE" },
  { name: "Bayeux PB", region: "NE" },
  { name: "Cabedelo PB", region: "NE" },
  { name: "Sousa PB", region: "NE" },
  { name: "Cajazeiras PB", region: "NE" },
  { name: "Guarabira PB", region: "NE" },
  { name: "Maceió AL", region: "NE" },
  { name: "Arapiraca AL", region: "NE" },
  { name: "Palmeira dos Índios AL", region: "NE" },
  { name: "Rio Largo AL", region: "NE" },
  { name: "União dos Palmares AL", region: "NE" },
  { name: "Penedo AL", region: "NE" },
  { name: "Coruripe AL", region: "NE" },
  { name: "Aracaju SE", region: "NE" },
  { name: "Nossa Senhora do Socorro SE", region: "NE" },
  { name: "Lagarto SE", region: "NE" },
  { name: "Itabaiana SE", region: "NE" },
  { name: "São Cristóvão SE", region: "NE" },
  { name: "Estância SE", region: "NE" },
  { name: "Tobias Barreto SE", region: "NE" },
  { name: "Teresina PI", region: "NE" },
  { name: "Parnaíba PI", region: "NE" },
  { name: "Picos PI", region: "NE" },
  { name: "Piripiri PI", region: "NE" },
  { name: "Floriano PI", region: "NE" },
  { name: "Barras PI", region: "NE" },

  // ===== NORTE =====
  { name: "Manaus AM", region: "N" },
  { name: "Parintins AM", region: "N" },
  { name: "Itacoatiara AM", region: "N" },
  { name: "Manacapuru AM", region: "N" },
  { name: "Coari AM", region: "N" },
  { name: "Tefé AM", region: "N" },
  { name: "Tabatinga AM", region: "N" },
  { name: "Belém PA", region: "N" },
  { name: "Ananindeua PA", region: "N" },
  { name: "Santarém PA", region: "N" },
  { name: "Marabá PA", region: "N" },
  { name: "Castanhal PA", region: "N" },
  { name: "Parauapebas PA", region: "N" },
  { name: "Abaetetuba PA", region: "N" },
  { name: "Cametá PA", region: "N" },
  { name: "Marituba PA", region: "N" },
  { name: "Bragança PA", region: "N" },
  { name: "Altamira PA", region: "N" },
  { name: "Tucuruí PA", region: "N" },
  { name: "Porto Velho RO", region: "N" },
  { name: "Ji-Paraná RO", region: "N" },
  { name: "Ariquemes RO", region: "N" },
  { name: "Vilhena RO", region: "N" },
  { name: "Cacoal RO", region: "N" },
  { name: "Rolim de Moura RO", region: "N" },
  { name: "Rio Branco AC", region: "N" },
  { name: "Cruzeiro do Sul AC", region: "N" },
  { name: "Sena Madureira AC", region: "N" },
  { name: "Tarauacá AC", region: "N" },
  { name: "Boa Vista RR", region: "N" },
  { name: "Rorainópolis RR", region: "N" },
  { name: "Caracaraí RR", region: "N" },
  { name: "Macapá AP", region: "N" },
  { name: "Santana AP", region: "N" },
  { name: "Laranjal do Jari AP", region: "N" },
  { name: "Palmas TO", region: "N" },
  { name: "Araguaína TO", region: "N" },
  { name: "Gurupi TO", region: "N" },
  { name: "Porto Nacional TO", region: "N" },
  { name: "Paraíso do Tocantins TO", region: "N" },
];

export function pickRandom<T>(arr: T[], n: number): T[] {
  const copy = [...arr];
  const out: T[] = [];
  while (out.length < n && copy.length > 0) {
    const idx = Math.floor(Math.random() * copy.length);
    out.push(copy.splice(idx, 1)[0]);
  }
  return out;
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/**
 * Retorna as cidades entrelaçadas por região (round-robin), garantindo
 * cobertura nacional mesmo quando a busca parar cedo. Cada região é
 * embaralhada independentemente para evitar viés.
 */
export function roundRobinCities(): CityEntry[] {
  const regions: CityEntry["region"][] = ["SE", "S", "CO", "NE", "N"];
  const buckets = regions.map((r) => shuffle(AUTO_CITIES.filter((c) => c.region === r)));
  const out: CityEntry[] = [];
  let added = true;
  let i = 0;
  while (added) {
    added = false;
    for (const b of buckets) {
      if (b[i]) {
        out.push(b[i]);
        added = true;
      }
    }
    i++;
  }
  return out;
}
